export const reviews = [
  {
    id: 1,
    name: "Rajesh Sharma",
    role: "CEO, Inflame India",
    text: "Dreams4u transformed our online presence completely. Our website now ranks #1 in Faridabad for industrial equipment. The team's attention to detail is remarkable!",
    rating: 5,
    project: "E-commerce Website",
    location: "Faridabad",
    avatar: "RS",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: 2,
    name: "Priya Singh",
    role: "Owner, Khatri Jewellers",
    text: "Our jewellery business saw a 300% increase in online inquiries after Dreams4u redesigned our website. Their SEO strategies really work wonders!",
    rating: 5,
    project: "Luxury E-commerce",
    location: "Ballabhgarh",
    avatar: "PS",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: 3,
    name: "Amit Verma",
    role: "Director, Oil Lube Systems",
    text: "Professional, punctual, and perfectionists! Our website loads in under 2 seconds and ranks on first page. Highly recommended for any business in Faridabad.",
    rating: 5,
    project: "Corporate Website",
    location: "Faridabad",
    avatar: "AV",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: 4,
    name: "Neha Kapoor",
    role: "Founder, Nut Cracker Group",
    text: "From concept to launch, the team was incredibly supportive. Our website looks stunning and performs even better. Great value for money!",
    rating: 5,
    project: "Food Business Portal",
    location: "Faridabad",
    avatar: "NK",
    color: "from-yellow-500 to-orange-500",
  },
  {
    id: 5,
    name: "Vikram Mehta",
    role: "Manager, Mahadev Tours",
    text: "Best website design company in Faridabad! They understood our travel business needs perfectly and delivered beyond expectations.",
    rating: 5,
    project: "Tour & Travel Website",
    location: "Faridabad",
    avatar: "VM",
    color: "from-red-500 to-rose-500",
  },
  {
    id: 6,
    name: "Sanjay Gupta",
    role: "Owner, Rods Media",
    text: "Working with Dreams4u was a game-changer. Our website's speed and user experience improved dramatically. Their ongoing support is exceptional.",
    rating: 5,
    project: "Media Company Website",
    location: "Faridabad",
    avatar: "SG",
    color: "from-indigo-500 to-violet-500",
  },
  {
    id: 7,
    name: "Deepak Kumar",
    rating: 5,
    text: "Dreams4u is an excellent website designing company. The team is highly professional, creative, and very supportive throughout the entire process. They understand requirements clearly and deliver clean, modern, and user-friendly websites on time. Highly recommended for anyone looking for reliable and high-quality web design services.",
  },
  {
    id: 8,
    name: "Shiv Kumar",
    rating: 5,
    text: "Greate experience, professional people with good value.. such a greate work carry on guys.",
  },
  {
    id: 9,
    name: "Rahul Sharma",
    rating: 4,
    text: "Great choice for your website design. Best website design company with 100% satisfaction.",
  },
];
