export const reviews = [
  {
    id: 1,
    name: "Abhishek Chaudhary",
    role: "",
    text: "We had an excellent experience working with Dream4U for our website project. The team is creative, responsive, and highly professional. They created a beautiful website that perfectly matches our brand image and business goals. The website runs smoothly, loads quickly, and is easy for customers to navigate. Their support after project completion has also been very reliable. We highly recommend Dream4U to anyone looking for high-quality website design services.",
    rating: 5,
    project: "E-commerce Website",
    location: "Faridabad",
    avatar: "RS",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: 2,
    name: "Nishant Rajput",
    role: "",
    text: "We are extremely happy with the website created by Dream4U. Their team delivered exactly what we wanted and even added extra features that improved the overall experience. The design is elegant, mobile responsive, and SEO-friendly. They kept us updated during every stage of the project and quickly responded to all our queries. It was a smooth and professional experience working with them. Highly recommended for web design services.",
    rating: 5,
    project: "Luxury E-commerce",
    location: "Ballabhgarh",
    avatar: "PS",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: 3,
    name: "Silky Rajput",
    role: "",
    text: "Dream4U is one of the best web design companies we have worked with. Their creativity, professionalism, and dedication are truly impressive. They created a beautiful and responsive website that works perfectly on all devices. The loading speed and overall user experience are excellent. The team also guided us with useful suggestions to improve our website performance. We are extremely satisfied with their service and would definitely work with them again.",
    rating: 5,
    project: "Corporate Website",
    location: "Faridabad",
    avatar: "AV",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: 4,
    name: "Kumkum Rajput",
    role: "",
    text: "We had a wonderful experience working with Dream4U. The designers are highly skilled and know how to create attractive and user-friendly websites. They paid attention to every small detail and made sure the final website matched our brand perfectly. Communication was smooth throughout the project, and they were always open to suggestions. The final result exceeded our expectations and helped improve our online presence significantly.",
    rating: 4,
    project: "Food Business Portal",
    location: "Faridabad",
    avatar: "NK",
    color: "from-yellow-500 to-orange-500",
  },
  {
    id: 5,
    name: "Alisha Sharma",
    role: "",
    text: "Dream4U designed an amazing website for our business with a modern and professional look. Their team understood our requirements perfectly and delivered everything on time. The website is fast, mobile-friendly, and very easy to manage. We have received many compliments from our customers after launching the new design. Their support team is also very helpful and responsive whenever we need changes or assistance. Highly recommended for anyone looking for creative and reliable website designers.🥰",
    rating: 5,
    project: "Tour & Travel Website",
    location: "Faridabad",
    avatar: "VM",
    color: "from-red-500 to-rose-500",
  },
  {
    id: 6,
    name: "Simran Rajput",
    role: "",
    text: "Dreams 4U is a reliable and professional web designing company. They pay attention to every small detail and provide innovative website solutions at reasonable prices. The staff is polite, knowledgeable, and always ready to help. I would highly recommend them to anyone looking for quality web development services.",
    rating: 5,
    project: "Media Company Website",
    location: "Faridabad",
    avatar: "SG",
    color: "from-indigo-500 to-violet-500",
  },
  {
    id: 7,
    name: "Deepak Kumar",
    rating: 5,
    text: "Dreams4u is an excellent website designing company. The team is highly professional, creative, and very supportive throughout the entire process. They understand requirements clearly and deliver clean, modern, and user-friendly websites on time. Highly recommended for anyone looking for reliable and high-quality web design services.",
  },
  {
    id: 8,
    name: "Shiv Kumar",
    rating: 5,
    text: "Greate experience, professional people with good value.. such a greate work carry on guys.",
  },
  {
    id: 9,
    name: "Rahul Sharma",
    rating: 4,
    text: "Great choice for your website design. Best website design company with 100% satisfaction.",
  },
];
